version: '3.9'
services:
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./php-server:/var/www/html
      - ./web-server/conf.d:/etc/nginx/conf.d
    links:
      - php-fpm
  php-fpm:
    image: php82fpm
    build:
      context: .
      dockerfile: ./web-server/Dockerfile
    container_name: php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./php-server:/var/www/html